baseURL = "https://tannerfilip.org/"
languageCode = "en-us"
title = "tanner filip"
theme = "hugo-theme-nix"
relativeUrls = true

[params]
  GithubID = "tannerfilip"
  GitlabId = "tannerfilip"
  TwitterID = "tannerfilip"
  LinkedInID = "tannerfilip"
  TelegramID = "tannerfilip"
  Name = "tanner filip"
  HeaderUsername = "visitor"
  headerhostname = "tannerfilip.org"
  Email = "tannerfilip@gmail.com"
  CvURL = "/resume.pdf"
  About = "Hi, I'm Tanner. I am a student at Western Governors University, studying Cloud & Systems Administration. I've been a contributor to the Mozilla project since 2008."

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/blog"
